NIMSP update

diff --git a/dc_data/scripts/nimsp/load-nimsp-update b/dc_data/scripts/nimsp/load-nimsp-update
--- a/dc_data/scripts/nimsp/load-nimsp-update
+++ b/dc_data/scripts/nimsp/load-nimsp-update
@@ -10,22 +10,16 @@ program=$(basename $0)
 USERNAME=datacommons
 DBNAME=nimsp
 
-# find the latest update as default
-if [ $(uname) = 'Darwin' ]; then
-    src=$(find /home/$USER/projects/datacommons/var/nimsp -depth 1 -type d -name '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]' | sort -r | head -n 1)
-else
-    src=$(find /home/datacommons/var/nimsp -type d -name '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]' | sort -r | head -n 1)
-fi
 
 set -e
 
 function usage {
     cat <<EOF
-Usage: $program [OPTION]...
+Usage: $program -s DIRECTORY [OPTION]...
 
 Options:
   -d DBNAME     Database (default $DBNAME)
-  -s DIRECTORY  Data directory to load from (default $src)
+  -s DIRECTORY  Data directory to load from (required)
   -p PASSWORD   Database password
   -U USERNAME   Database user name (default $USERNAME)
 
@@ -49,14 +43,15 @@ while getopts ":d:hs:p:U:" opt; do
 	*) usage 1;;
     esac
 done
-
-date=$(basename $src)
-update=$src/Update-${date}.sql 
-
-if [ ! -d $src ]; then
+if [ -z "$src" ]; then
+    echo "-s DIRECTORY is required" >&2
+    exit 1
+elif [ ! -d "$src" ]; then
     echo "No such directory $src" >&2
     exit 1
-fi
+fi 
+
+update=${src}/Update-20[0-9][0-9]-[01][0-9]-[0123][0-9].sql 
 if [ ! -f $update ]; then
     echo "No such file $update" >&2
     exit 1
@@ -67,6 +62,8 @@ if [ -z "$PASSWD" ]; then
     read PASSWD
 fi
 
+
+set -e
 echo Loading $update
 mysql -u $USERNAME --password=$PASSWD $DBNAME < $update
 
